In [1]:
from pathlib import Path

import pandas as pd

In [2]:
# Dataset
DATA_PATH = Path("../data/raw/online_retail_II.xlsx")

print(DATA_PATH.exists())
print(DATA_PATH)

True
../data/raw/online_retail_II.xlsx

In [3]:
# Feuilles EXCEL

excel_file = pd.ExcelFile(DATA_PATH)

excel_file.sheet_names

['Year 2009-2010', 'Year 2010-2011']

In [4]:
# Structure des feuilles excel

for sheet in excel_file.sheet_names:
    print(f"\n--- {sheet} ---")
    
    sample = pd.read_excel(
        DATA_PATH,
        sheet_name=sheet,
        nrows=5
    )
    
    display(sample)

--- Year 2009-2010 ---

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom

--- Year 2010-2011 ---

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [5]:
# Les colonnes sont : 

for sheet in excel_file.sheet_names:
    sample = pd.read_excel(
        DATA_PATH,
        sheet_name=sheet,
        nrows=5
    )
    
    print(f"\n{sheet}")
    print(sample.columns.tolist())

Year 2009-2010
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

Year 2010-2011
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [6]:
excel_file.sheet_names

['Year 2009-2010', 'Year 2010-2011']

In [7]:
sample.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'Price',
 'Customer ID',
 'Country']

In [8]:
# Chargement du dataset

df_2009_2010 = pd.read_excel(
    DATA_PATH,
    sheet_name="Year 2009-2010"
)

df_2010_2011 = pd.read_excel(
    DATA_PATH,
    sheet_name="Year 2010-2011"
)

print("2009-2010 :", df_2009_2010.shape)
print("2010-2011 :", df_2010_2011.shape)

2009-2010 : (525461, 8)
2010-2011 : (541910, 8)

In [9]:
# Data type

print(" 2009-2010 ")
df_2009_2010.info()

print("\n 2010-2011 ")
df_2010_2011.info()

 2009-2010
<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

 2010-2011
<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[us]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [10]:
# Valeurs manquantes :

print(" Valeurs manquantes 2009-2010 ")
display(df_2009_2010.isna().sum())

print(" Valeurs manquantes 2010-2011 ")
display(df_2010_2011.isna().sum())

 Valeurs manquantes 2009-2010

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

 Valeurs manquantes 2010-2011

Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64

Beaucoup de Customer ID manquants : On les gardes pour analyser les transactions mais on ne peut pas les garder pour des analyses clients .

In [11]:
# Verification des periodes : 

print("2009-2010")
print("Date minimum :", df_2009_2010["InvoiceDate"].min())
print("Date maximum :", df_2009_2010["InvoiceDate"].max())

print("\n2010-2011")
print("Date minimum :", df_2010_2011["InvoiceDate"].min())
print("Date maximum :", df_2010_2011["InvoiceDate"].max())

2009-2010
Date minimum : 2009-12-01 07:45:00
Date maximum : 2010-12-09 20:01:00

2010-2011
Date minimum : 2010-12-01 08:26:00
Date maximum : 2011-12-09 12:50:00

Il y a un chevauchement des dates du 1er au 9 décembre 2010.
Avant de concaténer les deux feuilles il faut verifier si : 
- Les transactions apparaissent deux fois ?
- Transactions différentes ? 
- Particularité du fichier ?

In [12]:
# Controle des infos : 
for name, df in [
    ("2009-2010", df_2009_2010),
    ("2010-2011", df_2010_2011)
]:
    print(f"\n {name} ")

    print("Nombre de lignes :", len(df))
    print("Factures distinctes :", df["Invoice"].nunique())
    print("Produits distincts :", df["StockCode"].nunique())
    print("Clients distincts :", df["Customer ID"].nunique())
    print("Pays distincts :", df["Country"].nunique())

    print("Quantité minimum :", df["Quantity"].min())
    print("Quantité maximum :", df["Quantity"].max())

    print("Prix minimum :", df["Price"].min())
    print("Prix maximum :", df["Price"].max())

 2009-2010
Nombre de lignes : 525461
Factures distinctes : 28816
Produits distincts : 4632
Clients distincts : 4383
Pays distincts : 40
Quantité minimum : -9600
Quantité maximum : 19152
Prix minimum : -53594.36
Prix maximum : 25111.09

 2010-2011
Nombre de lignes : 541910
Factures distinctes : 25900
Produits distincts : 4070
Clients distincts : 4372
Pays distincts : 38
Quantité minimum : -80995
Quantité maximum : 80995
Prix minimum : -11062.06
Prix maximum : 38970.0

Un prix unitaire negatif n'est pas normale.
et quantité négatif non plus. 
On va voir plus en détail ce a quoi c'est du.

In [13]:
# On conserve la provenance de chaque ligne avant de réunir les deux feuilles.
# On ajoute SourcePeriod pour savoir de quelle feuille originale vient une ligne pour la retraçer.

df_2009_2010["SourcePeriod"] = "2009-2010"
df_2010_2011["SourcePeriod"] = "2010-2011"

df_raw = pd.concat(
    [df_2009_2010, df_2010_2011],
    ignore_index=True
)

print("Dimensions du dataset complet :", df_raw.shape)

Dimensions du dataset complet : (1067371, 9)

In [14]:
# Verification des doublons : 

duplicate_count = df_raw.duplicated().sum()

print("Nombre de doublons exacts :", duplicate_count)

Nombre de doublons exacts : 12133

In [15]:
duplicate_rows = df_raw[df_raw.duplicated(keep=False)]

display(duplicate_rows.head(20))

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,SourcePeriod
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom,2009-2010
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom,2009-2010
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom,2009-2010
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom,2009-2010
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom,2009-2010
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom,2009-2010
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom,2009-2010
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom,2009-2010
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom,2009-2010
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom,2009-2010
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom,2009-2010
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom,2009-2010
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom,2009-2010

In [16]:
business_columns = [
    "Invoice",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "Price",
    "Customer ID",
    "Country"
]

duplicates_business = df_raw.duplicated(
    subset=business_columns,
    keep=False
)

print(
    "Lignes potentiellement dupliquées sur les colonnes métier :",
    duplicates_business.sum()
)

Lignes potentiellement dupliquées sur les colonnes métier : 67242

In [17]:
display(
    df_raw.loc[duplicates_business]
    .sort_values(["InvoiceDate", "Invoice", "StockCode"])
    .head(30)
)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,SourcePeriod
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom,2009-2010
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom,2009-2010
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,2009-2010
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom,2009-2010
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom,2009-2010
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom,2009-2010
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom,2009-2010
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom,2009-2010
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom,2009-2010
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom,2009-2010
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom,2009-2010
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom,2009-2010
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom,2009-2010
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom,2009-2010
669,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom,2009-2010
721,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom,2009-2010
723,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom,2009-2010
716,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom,2009-2010
725,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom,2009-2010
772,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom,2009-2010
856,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom,2009-2010
826,489536,21231,SWEETHEART CERAMIC TRINKET BOX,1,2009-12-01 12:13:00,1.25,16393.0,United Kingdom,2009-2010
840,489536,21231,SWEETHEART CERAMIC TRINKET BOX,1,2009-12-01 12:13:00,1.25,16393.0,United Kingdom,2009-2010
830,489536,21579,LOLITA DESIGN COTTON TOTE BAG,1,2009-12-01 12:13:00,2.25,16393.0,United Kingdom,2009-2010

In [18]:
# Verification chevauchement dates décembre 2010

overlap_2009_2010 = df_2009_2010[
    df_2009_2010["InvoiceDate"].between(
        "2010-12-01",
        "2010-12-09 23:59:59"
    )
]

overlap_2010_2011 = df_2010_2011[
    df_2010_2011["InvoiceDate"].between(
        "2010-12-01",
        "2010-12-09 23:59:59"
    )
]

print("Lignes décembre 2010 dans feuille 2009-2010 :", len(overlap_2009_2010))
print("Lignes décembre 2010 dans feuille 2010-2011 :", len(overlap_2010_2011))

Lignes décembre 2010 dans feuille 2009-2010 : 22523
Lignes décembre 2010 dans feuille 2010-2011 : 22523

In [19]:
print("Factures feuille 2009-2010 :", overlap_2009_2010["Invoice"].nunique())

print("Factures feuille 2010-2011 :",overlap_2010_2011["Invoice"].nunique())

Factures feuille 2009-2010 : 1088
Factures feuille 2010-2011 : 1088

In [20]:
common_invoices = set(overlap_2009_2010["Invoice"]).intersection(
    set(overlap_2010_2011["Invoice"])
)

print("Factures présentes dans les deux feuilles :", len(common_invoices))

Factures présentes dans les deux feuilles : 1088

Sur la periode les factures apparaissent sur les deux feuilles.

In [21]:
# Colonnes à comparer entre les deux feuilles

compare_columns = [
    "Invoice",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "Price",
    "Customer ID",
    "Country"
]

# On trie les deux périodes 
overlap_a = (
    overlap_2009_2010[compare_columns]
    .sort_values(compare_columns, na_position="last")
    .reset_index(drop=True)
)

overlap_b = (
    overlap_2010_2011[compare_columns]
    .sort_values(compare_columns, na_position="last")
    .reset_index(drop=True)
)

print("Même nombre de lignes :", len(overlap_a) == len(overlap_b))
print("Contenu strictement identique :", overlap_a.equals(overlap_b))

Même nombre de lignes : True
Contenu strictement identique : True

### Constat de qualité : 
- les deux feuilles couvrent une periode commune du 1er au 9 décembre 2010
- Cette période contient 22 523 lignes et 1 088 factures dans chacune des deux feuilles. 
- Les 1 088 numéros de facture sont présents dans les deux sources.

Vérification pour voir si les lignes sont strictement identiques

In [22]:
overlap_a.equals(overlap_b)

True

### Conclusion 

La période du 1er au 9 décembre 2010 est présente dans les deux feuilles du fichier original.

Les deux périodes contiennent exactement :

- 22 523 lignes ;
- 1 088 factures distinctes.

Après tri sur l’ensemble des colonnes métier, les deux sous-ensembles sont strictement identiques.


lors de l’intégration des deux feuilles, une seule occurrence de cette période sera conservée afin d’éviter un double comptage des transactions.

La feuille Year 2010-2011 sera conservée comme source de référence pour cette période de chevauchement.

### Comprendre les quantités negatives :

In [23]:
# Analyse des quantités négatives

negative_quantity = df_raw[df_raw["Quantity"] < 0]

print("Nombre de lignes avec quantité négative :", len(negative_quantity))
print("Nombre de factures concernées :", negative_quantity["Invoice"].nunique())

Nombre de lignes avec quantité négative : 22950
Nombre de factures concernées : 11684

In [24]:
display(
    negative_quantity[
        [
            "Invoice",
            "StockCode",
            "Description",
            "Quantity",
            "Price",
            "Customer ID",
            "Country",
            "InvoiceDate"
        ]
    ].head(30)
)

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country,InvoiceDate
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2.95,16321.0,Australia,2009-12-01 10:33:00
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,1.65,16321.0,Australia,2009-12-01 10:33:00
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,4.25,16321.0,Australia,2009-12-01 10:33:00
181,C489449,21896,POTTING SHED TWINE,-6,2.10,16321.0,Australia,2009-12-01 10:33:00
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2.95,16321.0,Australia,2009-12-01 10:33:00
183,C489449,21871,SAVE THE PLANET MUG,-12,1.25,16321.0,Australia,2009-12-01 10:33:00
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,1.25,16321.0,Australia,2009-12-01 10:33:00
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,0.85,16321.0,Australia,2009-12-01 10:33:00
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2.95,16321.0,Australia,2009-12-01 10:33:00
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,4.25,17592.0,United Kingdom,2009-12-01 10:44:00
197,C489459,90200D,PINK SWEETHEART BRACELET,-3,4.25,17592.0,United Kingdom,2009-12-01 10:44:00
198,C489459,90200B,BLACK SWEETHEART BRACELET,-3,4.25,17592.0,United Kingdom,2009-12-01 10:44:00
199,C489459,90200E,GREEN SWEETHEART BRACELET,-3,4.25,17592.0,United Kingdom,2009-12-01 10:44:00
200,C489459,90200C,BLUE SWEETHEART BRACELET,-3,4.25,17592.0,United Kingdom,2009-12-01 10:44:00
201,C489459,90185C,BLACK DIAMANTE EXPANDABLE RING,-3,4.25,17592.0,United Kingdom,2009-12-01 10:44:00
202,C489459,90185B,AMETHYST DIAMANTE EXPANDABLE RING,-3,4.25,17592.0,United Kingdom,2009-12-01 10:44:00
203,C489459,90003C,MIDNIGHT BLUE PAIR HEART HAIR SLIDE,-3,3.75,17592.0,United Kingdom,2009-12-01 10:44:00
204,C489459,90003D,CRYSTAL PAIR HEART HAIR SLIDES,-3,3.75,17592.0,United Kingdom,2009-12-01 10:44:00
205,C489459,90003B,ROSE COLOUR PAIR HEART HAIR SLIDES,-3,3.75,17592.0,United Kingdom,2009-12-01 10:44:00
206,C489459,90209C,PINK ENAMEL+GLASS HAIR COMB,-3,2.10,17592.0,United Kingdom,2009-12-01 10:44:00
207,C489459,90209A,PURPLE ENAMEL+GLASS HAIR COMB,-3,2.10,17592.0,United Kingdom,2009-12-01 10:44:00
208,C489459,90082D,DIAMANTE BOW BROOCH BLACK COLOUR,-2,6.35,17592.0,United Kingdom,2009-12-01 10:44:00
263,489464,21733,85123a mixed,-96,0.00,NaN,United Kingdom,2009-12-01 10:52:00
283,489463,71477,short,-240,0.00,NaN,United Kingdom,2009-12-01 10:52:00
284,489467,85123A,21733 mixed,-192,0.00,NaN,United Kingdom,2009-12-01 10:53:00
285,C489476,22149,FELTCRAFT 6 FLOWER FRIENDS,-6,2.10,13293.0,United Kingdom,2009-12-01 10:55:00
316,C489503,21540,DAIRY MAID CERAMIC BUTTER DISH,-2,4.25,16011.0,United Kingdom,2009-12-01 11:04:00
317,C489503,21533,RETRO SPOT LARGE MILK JUG,-1,4.95,16011.0,United Kingdom,2009-12-01 11:04:00
318,C489504,85083,KISS REINDEER SCANDINAVIAN STOCKING,-6,2.55,13916.0,United Kingdom,2009-12-01 11:10:00
399,C489518,20892,SET/3 TALL GLASS CANDLE HOLDER PINK,-2,12.75,15461.0,United Kingdom,2009-12-01 11:35:00

In [25]:
# Verification des factures : 

negative_invoice_check = (
    negative_quantity["Invoice"]
    .astype(str)
    .str.startswith("C")
    .value_counts()
)

display(negative_invoice_check)

Invoice
True     19493
False     3457
Name: count, dtype: int64

In [26]:
# Calculons les proportions : 

total_negative = len(negative_quantity)

negative_with_c = (
    negative_quantity["Invoice"]
    .astype(str)
    .str.startswith("C")
    .sum()
)

negative_without_c = total_negative - negative_with_c

print("Quantités négatives :", total_negative)
print("Avec facture C :", negative_with_c)
print("Sans facture C :", negative_without_c)

print(
    "Part avec facture C :",
    round(negative_with_c / total_negative * 100, 2),
    "%"
)

Quantités négatives : 22950
Avec facture C : 19493
Sans facture C : 3457
Part avec facture C : 84.94 %

## Construction du dataset consolidé

On a chevauchement de 22 523 lignes entre les deux feuilles pour la période du 1er au 9 décembre 2010.

Afin d'éviter tout doublons, une seule occurrence de cette période est conservée.

Le dataset consolidé contient :
- la feuille 2009-2010 jusqu'au 30 novembre 2010 ;
- l'intégralité de la feuille 2010-2011.

In [27]:
# Retrait de la période dupliquée dans la première feuille

df_2009_2010_unique = df_2009_2010[
    df_2009_2010["InvoiceDate"] < "2010-12-01"
].copy()

# Consolidation des deux périodes

df_consolidated = pd.concat(
    [
        df_2009_2010_unique,
        df_2010_2011
    ],
    ignore_index=True
)

print("Dataset brut :", len(df_raw))
print("Dataset consolidé :", len(df_consolidated))
print("Lignes retirées :", len(df_raw) - len(df_consolidated))

Dataset brut : 1067371
Dataset consolidé : 1044848
Lignes retirées : 22523

In [28]:
# verification de la periode : 
print("Date minimum :", df_consolidated["InvoiceDate"].min())
print("Date maximum :", df_consolidated["InvoiceDate"].max())

Date minimum : 2009-12-01 07:45:00
Date maximum : 2011-12-09 12:50:00

In [29]:
# Recalcul des quantités negative :
negative_quantity = df_consolidated[
    df_consolidated["Quantity"] < 0
]

print(
    "Nombre de lignes avec quantité négative :",
    len(negative_quantity)
)

print(
    "Nombre de factures concernées :",
    negative_quantity["Invoice"].nunique()
)

Nombre de lignes avec quantité négative : 22557
Nombre de factures concernées : 11684

In [30]:
total_negative = len(negative_quantity)

negative_with_c = (
    negative_quantity["Invoice"]
    .astype(str)
    .str.startswith("C")
    .sum()
)

negative_without_c = total_negative - negative_with_c

print("Quantités négatives :", total_negative)
print("Avec facture C :", negative_with_c)
print("Sans facture C :", negative_without_c)

print(
    "Part avec facture C :",
    round(negative_with_c / total_negative * 100, 2),
    "%"
)

Quantités négatives : 22557
Avec facture C : 19164
Sans facture C : 3393
Part avec facture C : 84.96 %

### constat sur les quantités négatives

Après suppression du chevauchement entre les deux feuilles:
le dataset consolidé contient 22 557 lignes avec une quantité négative, 
réparties sur 11 684 factures.

Parmi ces lignes :

- 19 164, soit 84,96 %, appartiennent à une facture dont l'identifiant commence par `C` ;
- 3 393, soit 15,04 %, possèdent une quantité négative sans facture commençant par `C`.

Les quantités négatives ne peuvent donc pas être assimilées automatiquement à des annulations clients.

Les 3 393 cas restants doivent être analysés avant de définir une règle de nettoyage.

In [31]:
# On isole les cas sans le C : 
negative_without_c_df = negative_quantity[
    ~negative_quantity["Invoice"]
    .astype(str)
    .str.startswith("C")
].copy()

print(
    "Nombre de lignes avec quantité négative sans facture C :",
    len(negative_without_c_df)
)

Nombre de lignes avec quantité négative sans facture C : 3393

In [32]:
# Descriptions : 
display(
    negative_without_c_df["Description"]
    .value_counts(dropna=False)
    .head(30)
)

Description
NaN                       2633
check                      121
damages                     83
?                           81
damaged                     78
missing                     27
sold as set on dotcom       20
Damaged                     17
smashed                      9
thrown away                  9
Unsaleable, destroyed.       9
dotcom                       8
damages?                     7
??                           7
crushed                      6
given away                   6
MIA                          5
Damages                      5
counted                      5
checked                      5
wet damaged                  5
ebay                         5
ebay sales                   4
No Stock                     3
Dotcom                       3
broken                       3
CHECK                        3
wet pallet                   3
lost                         2
wet                          2
Name: count, dtype: int64

In [33]:
display(
    negative_without_c_df["StockCode"]
    .astype(str)
    .value_counts()
    .head(30)
)

StockCode
22423      11
82494L      6
22719       6
46000M      5
84016       5
85017A      5
47566B      5
20852       5
85175       5
21830       5
71477       4
46000S      4
21768       4
84559D      4
84990       4
35972       4
79000       4
20713       4
21843       4
84406B      4
85172       4
72802C      4
79323GR     3
21098       3
85064       3
21493       3
21489       3
21490       3
51008       3
79030A      3
Name: count, dtype: int64

In [34]:
display(
    negative_without_c_df[
        [
            "Invoice",
            "StockCode",
            "Description",
            "Quantity",
            "Price",
            "Customer ID",
            "Country",
            "InvoiceDate"
        ]
    ].head(50)
)

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country,InvoiceDate
263,489464,21733,85123a mixed,-96,0.0,NaN,United Kingdom,2009-12-01 10:52:00
283,489463,71477,short,-240,0.0,NaN,United Kingdom,2009-12-01 10:52:00
284,489467,85123A,21733 mixed,-192,0.0,NaN,United Kingdom,2009-12-01 10:53:00
470,489521,21646,NaN,-50,0.0,NaN,United Kingdom,2009-12-01 11:44:00
3114,489655,20683,NaN,-44,0.0,NaN,United Kingdom,2009-12-01 17:26:00
3162,489660,35956,lost,-1043,0.0,NaN,United Kingdom,2009-12-01 17:43:00
3168,489663,35605A,damages,-117,0.0,NaN,United Kingdom,2009-12-01 18:02:00
4296,489806,18010,NaN,-770,0.0,NaN,United Kingdom,2009-12-02 12:42:00
4538,489820,21133,invcd as 84879?,-720,0.0,NaN,United Kingdom,2009-12-02 13:23:00
4566,489821,85049G,NaN,-240,0.0,NaN,United Kingdom,2009-12-02 13:25:00
6556,489899,79323GR,sold as gold,-954,0.0,NaN,United Kingdom,2009-12-03 09:41:00
6576,489901,21098,NaN,-200,0.0,NaN,United Kingdom,2009-12-03 09:47:00
6911,490007,84347,21494,-720,0.0,NaN,United Kingdom,2009-12-03 12:09:00
7205,490016,21982,NaN,-1012,0.0,NaN,United Kingdom,2009-12-03 12:30:00
7559,490055,20620,NaN,-25,0.0,NaN,United Kingdom,2009-12-03 13:22:00
8553,490084,85064,NaN,-89,0.0,NaN,United Kingdom,2009-12-03 15:37:00
9308,490130,21493,lost?,-600,0.0,NaN,United Kingdom,2009-12-03 18:28:00
9667,490146,21558,NaN,-169,0.0,NaN,United Kingdom,2009-12-04 09:29:00
10508,490165,21493,NaN,-106,0.0,NaN,United Kingdom,2009-12-04 11:32:00
11973,490354,21489,NaN,-23,0.0,NaN,United Kingdom,2009-12-04 16:39:00
12237,490379,21490,NaN,-44,0.0,NaN,United Kingdom,2009-12-05 13:26:00
12299,490384,84721,NaN,-42,0.0,NaN,United Kingdom,2009-12-05 14:00:00
14480,490540,37446,NaN,-725,0.0,NaN,United Kingdom,2009-12-07 09:24:00
15883,490713,84347,NaN,-20,0.0,NaN,United Kingdom,2009-12-07 15:26:00
15908,490715,22158,NaN,-30,0.0,NaN,United Kingdom,2009-12-07 15:27:00
16185,490735,35976B,NaN,-60,0.0,NaN,United Kingdom,2009-12-07 17:12:00
16186,490736,35983,NaN,-200,0.0,NaN,United Kingdom,2009-12-07 17:13:00
17427,490765,21450,damaged,-31,0.0,NaN,United Kingdom,2009-12-08 10:59:00
17428,490766,51008,wet,-200,0.0,NaN,United Kingdom,2009-12-08 11:06:00
19312,490975,15059A,NaN,-126,0.0,NaN,United Kingdom,2009-12-08 16:41:00
19313,490976,84571,NaN,-120,0.0,NaN,United Kingdom,2009-12-08 16:42:00
20759,491046,20987,NaN,-100,0.0,NaN,United Kingdom,2009-12-09 10:03:00
20760,491047,21982,NaN,-50,0.0,NaN,United Kingdom,2009-12-09 10:04:00
20970,491065,84855,MIA,-108,0.0,NaN,United Kingdom,2009-12-09 11:59:00
20975,491066,35949,NaN,-67,0.0,NaN,United Kingdom,2009-12-09 12:17:00
21646,491108,84922,NaN,-360,0.0,NaN,United Kingdom,2009-12-09 14:29:00
22088,491128,21490,NaN,-20,0.0,NaN,United Kingdom,2009-12-09 16:00:00
22116,491137,21489,NaN,-8,0.0,NaN,United Kingdom,2009-12-09 16:25:00
22133,491141,22174,NaN,-58,0.0,NaN,United Kingdom,2009-12-09 16:43:00
22854,491167,17013A,NaN,-45,0.0,NaN,United Kingdom,2009-12-10 11:09:00
23542,491206,84841,NaN,-54,0.0,NaN,United Kingdom,2009-12-10 14:10:00
23988,491355,17014C,NaN,-96,0.0,NaN,United Kingdom,2009-12-10 15:52:00
24941,491451,20940,NaN,-46,0.0,NaN,United Kingdom,2009-12-11 11:09:00
26004,491638,21353,NaN,-136,0.0,NaN,United Kingdom,2009-12-11 15:59:00
26005,491639,20668,NaN,-1395,0.0,NaN,United Kingdom,2009-12-11 16:02:00
28111,491732,79030A,smashed,-350,0.0,NaN,United Kingdom,2009-12-14 10:00:00
29109,491817,72487,NaN,-322,0.0,NaN,United Kingdom,2009-12-14 13:37:00
32104,491972,21100,bad quality,-76,0.0,NaN,United Kingdom,2009-12-14 18:43:00
32105,491974,72752B,NaN,-21,0.0,NaN,United Kingdom,2009-12-14 18:44:00
32106,491975,72752C,NaN,-24,0.0,NaN,United Kingdom,2009-12-14 18:44:00

In [35]:
display(
    negative_without_c_df[
        [
            "Invoice",
            "StockCode",
            "Description",
            "Quantity",
            "Price",
            "Customer ID",
            "Country",
            "InvoiceDate"
        ]
    ]
    .sort_values("Quantity")
    .head(30)
)

,Invoice,StockCode,Description,Quantity,Price,Customer ID,Country,InvoiceDate
728468,556691,23005,printing smudges/thrown away,-9600,0.0,NaN,United Kingdom,2011-06-14 10:37:00
728467,556690,23005,printing smudges/thrown away,-9600,0.0,NaN,United Kingdom,2011-06-14 10:37:00
303996,519017,22759,NaN,-9600,0.0,NaN,United Kingdom,2010-08-13 09:14:00
156488,504311,22197,NaN,-9200,0.0,NaN,United Kingdom,2010-04-12 14:39:00
728466,556687,23003,Printing smudges/thrown away,-9058,0.0,NaN,United Kingdom,2011-06-14 10:36:00
428975,530348,16235,?,-9000,0.0,NaN,United Kingdom,2010-11-02 15:48:00
194372,507913,10120,Zebra invcing error,-9000,0.0,NaN,United Kingdom,2010-05-11 17:16:00
437008,531177,20852,Given away,-8800,0.0,NaN,United Kingdom,2010-11-05 14:40:00
258814,514363,84016,Ebay sales by the box.,-7100,0.0,NaN,United Kingdom,2010-07-01 18:07:00
269558,515462,20852,given away,-7000,0.0,NaN,United Kingdom,2010-07-12 15:47:00
437009,531178,22126,NaN,-6400,0.0,NaN,United Kingdom,2010-11-05 14:40:00
303995,519016,22752,NaN,-6000,0.0,NaN,United Kingdom,2010-08-13 09:13:00
618756,546152,72140F,throw away,-5368,0.0,NaN,United Kingdom,2011-03-09 17:25:00
136409,502457,84016,ebay sales,-5200,0.0,NaN,United Kingdom,2010-03-24 14:20:00
269557,515463,22126,given away,-5000,0.0,NaN,United Kingdom,2010-07-12 15:47:00
269559,515464,22126,given away,-5000,0.0,NaN,United Kingdom,2010-07-12 15:48:00
304002,519021,22756,NaN,-5000,0.0,NaN,United Kingdom,2010-08-13 09:17:00
304001,519023,22758,NaN,-5000,0.0,NaN,United Kingdom,2010-08-13 09:17:00
304000,519022,22757,NaN,-5000,0.0,NaN,United Kingdom,2010-08-13 09:17:00
303999,519020,22755,NaN,-5000,0.0,NaN,United Kingdom,2010-08-13 09:17:00
303998,519019,22754,NaN,-5000,0.0,NaN,United Kingdom,2010-08-13 09:16:00
303997,519018,22753,NaN,-5000,0.0,NaN,United Kingdom,2010-08-13 09:15:00
136410,502458,84016,ebay sales,-5000,0.0,NaN,United Kingdom,2010-03-24 14:21:00
302041,518785,C3,NaN,-4999,0.0,NaN,United Kingdom,2010-08-11 16:55:00
934319,573596,79323W,"Unsaleable, destroyed.",-4830,0.0,NaN,United Kingdom,2011-10-31 15:17:00
158106,504455,22528,NaN,-4800,0.0,NaN,United Kingdom,2010-04-13 15:34:00
158144,504457,22558,NaN,-4800,0.0,NaN,United Kingdom,2010-04-13 15:35:00
332334,521867,35015,wet damages,-4354,0.0,NaN,United Kingdom,2010-09-09 11:03:00
95372,498394,22433,my error - connor,-4200,0.0,NaN,United Kingdom,2010-02-18 15:10:00
68648,495464,72024HC,NaN,-3669,0.0,NaN,United Kingdom,2010-01-25 12:07:00